/* ``````````` ## Development By el8rbawY ## ```````````*/
// normal  => مركبات عادية يتم عرضها في المعرض
// job     => مركبات خاصة بوظائف معينة لا تعرض في المعرض ولكن يمكن امتلاكها
// faction => مركبات الطوارئ بمعرض خاص ولا يمكن لأي حد شراؤها

const dealership = {
   vehicles: [ // send to client with with 'NewStart_Phone:initial-server'
      {
         id: 1,
         vehType: 'car',
         type: 'normal',
         category: 'small',
         name: 'Tata Nano',
         release: 2019,
         price: 5000,
         level: 5,
         hash: 'panto',
         acceleration: 67.50,
         braking: 20,
         handling: 59.70,
         maxKG: 10
      },
      {
         id: 2,
         vehType: 'car',
         type: 'normal',
         category: 'small',
         name: 'Mini Cooper',
         release: 2020,
         price: 10000,
         hash: 'issi2',
         level: 5,
         acceleration: 57.50,
         braking: 20,
         handling: 62.12,
         maxKG: 10
      },
      {
         id: 3,
         vehType: 'car',
         type: 'normal',
         category: 'coupe',
         name: 'Hyundai Tiburon',
         release: 2008,
         price: 30000,
         hash: 'prairie',
         level: 10,
         acceleration: 55,
         braking: 20,
         handling: 59.09,
         maxKG: 20
      },
      {
         id: 4,
         vehType: 'car',
         type: 'normal',
         name: 'Jaguar XF',
         category: 'coupe',
         release: 2015,
         price: 65000,
         hash: 'felon2',
         level: 15,
         acceleration: 60,
         braking: 30,
         handling: 75.76,
         maxKG: 20
      },
      {
         id: 5,
         vehType: 'car',
         type: 'normal',
         category: 'coupe',
         name: 'Jaguar XK',
         release: 2014,
         price: 65000,
         hash: 'f620',
         level: 15,
         acceleration: 60,
         braking: 30,
         handling: 75.76,
         maxKG: 20
      },
      {
         id: 6,
         vehType: 'car',
         type: 'normal',
         category: 'sport',
         name: 'Ford Mustang',
         release: 2020,
         price: 188000,
         hash: 'dominator',
         level: 20,
         acceleration: 72.50,
         braking: 26.67,
         handling: 68.18,
         maxKG: 20
      },
      {
         id: 7,
         vehType: 'car',
         type: 'normal',
         category: 'classic',
         name: 'Albany Emperor',
         release: 2012,
         price: 20000,
         hash: 'emperor',
         level: 15,
         acceleration: 35.00,
         braking: 20.00,
         handling: 57.58,
         maxKG: 20
      },
      {
         id: 8,
         vehType: 'motorcycle',
         type: 'normal',
         category: 'sport',
         name: 'Pegassi Bati',
         release: 2020,
         price: 200000,
         hash: 'bati',
         level: 25,
         acceleration: 75.00,
         braking: 46.67,
         handling: 70.30,
         maxKG: 5
      },
      {
         id: 9,
         vehType: 'motorcycle',
         type: 'normal',
         category: 'dirt',
         name: 'Nemesis Monster',
         release: 2016,
         price: 100000,
         hash: 'nemesis',
         level: 23,
         acceleration: 75.00,
         braking: 40.00,
         handling: 59.09,
         maxKG: 5
      },
      {
         id: 10,
         vehType: 'truck',
         type: 'normal',
         category: 'cargo250',
         name: 'MTL Pounder',
         release: 2019,
         price: 680000,
         hash: 'pounder2',
         level: 50,
         acceleration: 40.00,
         braking: 8.33,
         handling: 51.52,
         maxKG: 250
      },
      {
         id: 11,
         vehType: 'truck',
         type: 'normal',
         category: 'cargo250',
         name: 'Maibatsu Mule',
         release: 2015,
         price: 680000,
         hash: 'mule3',
         level: 50,
         acceleration: 27.50,
         braking: 8.33,
         handling: 45.45,
         maxKG: 250
      },
      {
         id: 12,
         vehType: 'truck',
         type: 'normal',
         category: 'head',
         name: 'Phantom',
         release: 2014,
         price: 690000,
         hash: 'phantom',
         level: 39,
         acceleration: 52.50,
         braking: 26.67,
         handling: 50.00,
         maxKG: 20
      },
      {
         id: 13,
         vehType: 'truck',
         type: 'normal',
         category: 'cargo250',
         name: 'Rallytruck',
         release: 2017,
         price: 680000,
         hash: 'rallytruck',
         level: 50,
         acceleration: 82.50,
         braking: 20.00,
         handling: 69.70,
         maxKG: 250
      },
      {
         id: 15,
         vehType: 'truck',
         type: 'job',
         name: 'Tow Truck',
         release: 2010,
         price: 150000,
         hash: 'towtruck',
         speed: 100,
         acceleration: 37.50,
         braking: 8.33,
         handling: 48.48,
         maxKG: 35
      },
      {
         id: 16,
         vehType: 'boat',
         type: 'store',
         category: 'luxury',
         name: 'Shitzu Longfin',
         release: 2020,
         price: 1400000,
         hash: 'longfin',
         level: 30,
         acceleration: 97.50,
         braking: 0,
         handling: 100,
         maxKG: 160
      },
      {
         id: 17,
         vehType: 'boat',
         type: 'normal',
         category: 'kayaks',
         name: 'Rigid inflatable',
         release: 2016,
         price: 65000,
         hash: 'dinghy2',
         level: 14,
         acceleration: 87,
         braking: 0,
         handling: 55,
         maxKG: 40,
         upCoordZ: 0.5
      },
      {
         id: 18,
         vehType: 'boat',
         type: 'normal',
         category: 'kayaks',
         name: 'Rigid inflatable X',
         release: 2018,
         price: 100000,
         hash: 867467158,
         level: 15,
         acceleration: 87,
         braking: 0,
         handling: 55,
         maxKG: 40,
         upCoordZ: 0.5
      },
      {
         id: 19,
         vehType: 'boat',
         type: 'normal',
         category: 'jetski',
         name: 'Seashark Lifeguard',
         release: 2021,
         price: 50000,
         hash: 'seashark3',
         level: 10,
         acceleration: 69,
         braking: 0,
         handling: 7,
         maxKG: 10,
         upCoordZ: 1
      },
      {
         id: 20,
         vehType: 'boat',
         type: 'normal',
         category: 'luxury',
         name: 'Lampadati Toro',
         release: 2020,
         price: 1400000,
         hash: 'toro2',
         level: 35,
         acceleration: 97.50,
         braking: 0,
         handling: 43.33,
         maxKG: 160,
         upCoordZ: -0.5
      },
      {
         id: 21,
         vehType: 'boat',
         type: 'normal',
         category: 'other',
         name: 'Shitzu Jetmax',
         release: 2019,
         price: 850000,
         hash: 'jetmax',
         level: 30,
         acceleration: 97.50,
         braking: 0,
         handling: 43.33,
         maxKG: 120
      },
      {
         id: 22,
         vehType: 'truck',
         type: 'job',
         name: 'MTL Flatbed',
         release: 2015,
         price: 300000,
         hash: 'flatbed',
         speed: 100,
         acceleration: 35.00,
         braking: 8.33,
         handling: 50.00,
         maxKG: 40
      },
      {
         id: 23,
         vehType: 'car',
         type: 'faction',
         name: 'دورية شارجر',
         level: 0,
         release: 2014,
         price: 0,
         hash: 'i14chargerbb',
         speed: 200,
         acceleration: 60,
         braking: 30,
         handling: 75.76,
         maxKG: 60
      },
      {
         id: 24,
         vehType: 'plane',
         type: 'faction',
         name: 'مروحية',
         level: 0,
         release: 2020,
         price: 0,
         hash: 'eheli',
         acceleration: 83.50,
         braking: 0,
         handling: 66.67,
         maxKG: 60
      },
      {
         id: 25,
         vehType: 'motorcycle',
         type: 'faction',
         name: 'دراجة المرور',
         level: 0,
         release: 2023,
         price: 0,
         hash: 'policeb',
         speed: 150,
         acceleration: 67.50,
         braking: 36.67,
         handling: 57.58,
         maxKG: 10
      },
      {
         id: 26,
         vehType: 'car',
         type: 'faction',
         name: 'فان الإسعاف',
         level: 0,
         release: 2020,
         price: 0,
         hash: 'emsnspeedo',
         acceleration: 60,
         braking: 30,
         handling: 75.76,
         maxKG: 60
      },
      {
         id: 27,
         vehType: 'car',
         type: 'faction',
         name: 'مدرعة القوات الخاصة',
         level: 0,
         release: 2022,
         price: 0,
         hash: 'riot',
         acceleration: 30.00,
         braking: 8.33,
         handling: 50.00,
         maxKG: 80
      },
      {
         id: 28,
         vehType: 'car',
         type: 'faction',
         name: 'دورية تاهو',
         level: 0,
         release: 2023,
         price: 0,
         hash: 'i20tahoebb',
         speed: 200,
         acceleration: 60,
         braking: 30,
         handling: 75.76,
         maxKG: 60
      },
      {
         id: 29,
         vehType: 'car',
         type: 'faction',
         name: 'دورية فورد اكسبلور',
         level: 0,
         release: 2023,
         price: 0,
         hash: 'tr16fpiubb',
         acceleration: 60,
         braking: 30,
         handling: 75.76,
         maxKG: 60
      },
      {
         id: 29,
         vehType: 'car',
         type: 'faction',
         name: 'دورية دودج',
         level: 0,
         release: 2018,
         price: 0,
         hash: 'tr18chargerbb',
         acceleration: 60,
         braking: 30,
         handling: 75.76,
         maxKG: 60
      },
      {
         id: 30,
         vehType: 'car',
         type: 'faction',
         name: 'دورية فورد كروان',
         level: 0,
         release: 2013,
         price: 0,
         hash: 'w11cvpipbb',
         speed: 200,
         acceleration: 60,
         braking: 30,
         handling: 75.76,
         maxKG: 40
      },
      {
         id: 31,
         vehType: 'car',
         type: 'faction',
         name: 'دورية تندرا',
         level: 0,
         release: 2023,
         price: 0,
         hash: '23tundrabb',
         acceleration: 60,
         braking: 30,
         handling: 75.76,
         maxKG: 80
      },
      {
         id: 32,
         vehType: 'car',
         type: 'faction',
         name: 'دورية تورس',
         level: 0,
         release: 2023,
         price: 0,
         hash: 'i18fpisbb',
         acceleration: 60,
         braking: 30,
         handling: 75.76,
         maxKG: 60
      },
      {
         id: 33,
         vehType: 'car',
         type: 'faction',
         name: 'دورية دودج دورانجو',
         level: 0,
         release: 2023,
         price: 0,
         hash: 'whelen21durangobb',
         speed: 200,
         acceleration: 60,
         braking: 30,
         handling: 75.76,
         maxKG: 60
      },
      {
         id: 34,
         vehType: 'motorcycle',
         type: 'normal',
         category: 'sport',
         name: 'Nagasaki Carbon',
         release: 2022,
         price: 200000,
         hash: 'carbonrs',
         level: 25,
         acceleration: 75.00,
         braking: 43.33,
         handling: 65.15,
         maxKG: 5
      },
      {
         id: 35,
         vehType: 'motorcycle',
         type: 'normal',
         category: 'other',
         name: 'Western Bagger',
         release: 2015,
         price: 110000,
         hash: 'bagger',
         level: 15,
         acceleration: 52.50,
         braking: 40.00,
         handling: 50.00,
         maxKG: 5
      },
      {
         id: 36,
         vehType: 'motorcycle',
         type: 'normal',
         category: 'cruiser',
         name: 'Western Daemon',
         release: 2018,
         price: 100000,
         hash: 'daemon',
         level: 15,
         acceleration: 65.00,
         braking: 20.00,
         handling: 56.06,
         maxKG: 5
      },
      {
         id: 37,
         vehType: 'motorcycle',
         type: 'normal',
         category: 'cruiser',
         name: 'Principe Diabolus',
         release: 2021,
         price: 200000,
         hash: 'diablous',
         level: 25,
         acceleration: 78.00,
         braking: 40.00,
         handling: 59.09,
         maxKG: 5
      },
      {
         id: 38,
         vehType: 'motorcycle',
         type: 'normal',
         category: 'dirt',
         name: 'Pegassi Esskey',
         release: 2021,
         price: 150000,
         hash: 'esskey',
         level: 23,
         acceleration: 73.75,
         braking: 40.00,
         handling: 65.15,
         maxKG: 5
      },
      {
         id: 39,
         vehType: 'motorcycle',
         type: 'normal',
         category: 'scooters',
         name: 'Faggio Sport',
         release: 2022,
         price: 10000,
         hash: 'faggio',
         acceleration: 49.38,
         braking: 13.33,
         handling: 51.52,
         maxKG: 5
      },
      {
         id: 40,
         vehType: 'motorcycle',
         type: 'normal',
         category: 'scooters',
         name: 'Pegassi Faggio',
         release: 2015,
         price: 7000,
         hash: 'faggio2',
         acceleration: 25.00,
         braking: 13.33,
         handling: 48.48,
         maxKG: 5
      },
      {
         id: 41,
         vehType: 'car',
         type: 'normal',
         category: 'sport',
         name: 'Grotti Proto',
         release: 2020,
         price: 1500000,
         hash: 'prototipo',
         level: 80,
         acceleration: 93.75,
         braking: 36.67,
         handling: 81.82,
         maxKG: 20
      },
      {
         id: 42,
         vehType: 'car',
         type: 'normal',
         category: 'small',
         name: 'BF Club',
         release: 2013,
         price: 5000,
         hash: 'club',
         level: 2,
         acceleration: 59.38,
         braking: 24.00,
         handling: 62.12,
         maxKG: 10
      },
      {
         id: 43,
         vehType: 'car',
         type: 'normal',
         category: 'small',
         name: 'Grotti Brioso',
         release: 2020,
         price: 10000,
         hash: 'brioso',
         level: 7,
         acceleration: 72.50,
         braking: 20.00,
         handling: 69.70,
         maxKG: 10
      },
      {
         id: 44,
         vehType: 'car',
         type: 'normal',
         category: 'coupe',
         name: 'Karin Previon',
         release: 2017,
         price: 50000,
         hash: 'previon',
         level: 10,
         acceleration: 79.63,
         braking: 28.33,
         handling: 75.35,
         maxKG: 20
      },
      {
         id: 45,
         vehType: 'car',
         type: 'normal',
         category: 'classic_sport',
         name: 'Bravado Gauntlet',
         release: 2012,
         price: 75000,
         hash: 'gauntlet3',
         level: 15,
         acceleration: 70.00,
         braking: 30.00,
         handling: 75.76,
         maxKG: 20
      },
      {
         id: 46,
         vehType: 'car',
         type: 'normal',
         category: 'classic_sport',
         name: 'Declasse Turbo',
         release: 2013,
         price: 75000,
         hash: 'sabregt',
         level: 15,
         acceleration: 70.00,
         braking: 26.67,
         handling: 68.18,
         maxKG: 20
      },
      {
         id: 47,
         vehType: 'car',
         type: 'normal',
         category: 'cargo60',
         name: 'Vapid Slamvan',
         release: 2010,
         price: 98000,
         hash: 'slamvan3',
         level: 16,
         acceleration: 62.50,
         braking: 20.00,
         handling: 50.00,
         maxKG: 60
      },
      {
         id: 48,
         vehType: 'car',
         type: 'normal',
         category: 'coupe',
         name: 'Vapid ASP',
         release: 2015,
         price: 60000,
         hash: 'dominator7',
         level: 15,
         acceleration: 85.50,
         braking: 30.67,
         handling: 75.50,
         maxKG: 20
      },
      {
         id: 49,
         vehType: 'car',
         type: 'normal',
         category: 'off_road',
         name: 'BF Dubsta',
         release: 2022,
         price: 1500000,
         hash: 'dubsta3',
         level: 40,
         acceleration: 70.00,
         braking: 20.00,
         handling: 60.61,
         maxKG: 40
      },
      {
         id: 50,
         vehType: 'car',
         type: 'normal',
         category: 'cargo60',
         name: 'Karin Everon',
         release: 2020,
         price: 100000,
         hash: 'everon',
         level: 18,
         acceleration: 73.75,
         braking: 10.00,
         handling: 62.12,
         maxKG: 60
      },
      {
         id: 51,
         vehType: 'car',
         type: 'normal',
         category: 'cargo40',
         name: 'Karin Rebel',
         release: 2016,
         price: 21000,
         hash: 'rebel2',
         level: 5,
         acceleration: 50.00,
         braking: 20.00,
         handling: 62.12,
         maxKG: 40
      },
      {
         id: 52,
         vehType: 'car',
         type: 'normal',
         category: 'cargo80',
         name: 'Vapid Sandking',
         release: 2023,
         price: 165000,
         hash: 'sandking2',
         level: 19,
         acceleration: 50.00,
         braking: 20.00,
         handling: 60.61,
         maxKG: 80
      },
      {
         id: 53,
         vehType: 'car',
         type: 'normal',
         category: 'cargo60',
         name: 'Vapid Riata',
         release: 2020,
         price: 95000,
         hash: 'riata',
         level: 16,
         acceleration: 62.50,
         braking: 10.00,
         handling: 62.12,
         maxKG: 60
      },
      {
         id: 54,
         vehType: 'car',
         type: 'normal',
         category: 'big',
         name: 'Baller LWB',
         release: 2023,
         price: 1400000,
         hash: 'baller4',
         level: 50,
         acceleration: 67.50,
         braking: 19.00,
         handling: 60.61,
         maxKG: 40
      },
      {
         id: 55,
         vehType: 'car',
         type: 'normal',
         category: 'big',
         name: 'Canis Seminole',
         release: 2018,
         price: 200000,
         hash: 'seminole2',
         level: 15,
         acceleration: 50.00,
         braking: 26.67,
         handling: 60.61,
         maxKG: 40
      },
      {
         id: 56,
         vehType: 'car',
         type: 'normal',
         category: 'sedan',
         name: 'Declasse Asea',
         release: 2018,
         price: 8000,
         hash: 'asea',
         level: 2,
         acceleration: 50.00,
         braking: 13.33,
         handling: 62.12,
         maxKG: 20
      },
      {
         id: 57,
         vehType: 'car',
         type: 'normal',
         category: 'sedan',
         name: 'Karin Asterope',
         release: 2019,
         price: 140000,
         hash: 'asterope',
         level: 15,
         acceleration: 50.00,
         braking: 30.00,
         handling: 75.76,
         maxKG: 20
      },
      {
         id: 58,
         vehType: 'car',
         type: 'normal',
         category: 'sedan',
         name: 'Obey Tailgater',
         release: 2020,
         price: 100000,
         hash: 'tailgater2',
         level: 12,
         acceleration: 82.00,
         braking: 33.00,
         handling: 76.00,
         maxKG: 20
      },
      {
         id: 59,
         vehType: 'car',
         type: 'normal',
         category: 'sedan',
         name: 'Karin Kuruma',
         release: 2021,
         price: 140000,
         hash: 'kuruma',
         level: 12,
         acceleration: 77.50,
         braking: 16.67,
         handling: 74.24,
         maxKG: 20
      },
      {
         id: 60,
         vehType: 'car',
         type: 'normal',
         category: 'sedan',
         name: 'Sultan Classic',
         release: 2015,
         price: 140000,
         hash: 'sultan2',
         level: 12,
         acceleration: 82.50,
         braking: 16.67,
         handling: 75.61,
         maxKG: 20
      },
      {
         id: 61,
         vehType: 'car',
         type: 'normal',
         category: 'sport',
         name: 'Audi R8',
         release: 2021,
         price: 700000,
         hash: 'r820',
         level: 45,
         acceleration: 93.75,
         braking: 36.67,
         handling: 81.82,
         maxKG: 20
      },
      {
         id: 62,
         vehType: 'plane',
         type: 'normal',
         category: 'helicopters',
         name: 'SuperVolito',
         release: 2023,
         price: 650000,
         hash: 'supervolito',
         level: 35,
         acceleration: 71.50,
         braking: 0,
         handling: 58.00,
         maxKG: 40
      },
      {
         id: 63,
         vehType: 'plane',
         type: 'normal',
         category: 'turbo',
         name: 'Mammatus',
         release: 2015,
         price: 220000,
         hash: 'mammatus',
         level: 20,
         acceleration: 22.00,
         braking: 15.00,
         handling: 47.00,
         maxKG: 40
      },
      {
         id: 64,
         vehType: 'plane',
         type: 'normal',
         category: 'hydro',
         name: 'Sparrow',
         release: 2020,
         price: 500000,
         hash: 'seasparrow',
         level: 35,
         acceleration: 83.33,
         braking: 0,
         handling: 69.00,
         maxKG: 40
      },
      {
         id: 65,
         vehType: 'plane',
         type: 'normal',
         category: 'other',
         name: 'Ultralight',
         release: 2023,
         price: 25000,
         hash: 'microlight',
         level: 15,
         acceleration: 45.50,
         braking: 36.00,
         handling: 58.00,
         maxKG: 5
      },
      {
         id: 66,
         vehType: 'plane',
         type: 'normal',
         category: 'helicopters',
         name: 'Buzzard',
         release: 2023,
         price: 650000,
         hash: 'buzzard2',
         level: 35,
         acceleration: 87.00,
         braking: 0,
         handling: 71.00,
         maxKG: 40
      },
      {
         id: 67,
         vehType: 'car',
         type: 'faction',
         name: 'فان نقل السجن',
         level: 0,
         release: 2015,
         price: 0,
         hash: 'ambo',
         speed: 0,
         acceleration: 60,
         braking: 30,
         handling: 75.76,
         maxKG: 40
      },
      {
         id: 67,
         vehType: 'car',
         type: 'faction',
         name: 'بوكس الإسعاف',
         level: 0,
         release: 2023,
         price: 0,
         hash: 'f450ambo',
         speed: 0,
         acceleration: 60,
         braking: 30,
         handling: 75.76,
         maxKG: 35
      },
      {
         id: 68,
         vehType: 'boat',
         type: 'faction',
         name: 'قارب الإسعاف',
         level: 0,
         release: 2021,
         price: 0,
         hash: 'predator',
         acceleration: 82.35,
         braking: 0,
         handling: 44.00,
         maxKG: 35,
         Z_Dealership: 0.06
      },
      {
         id: 69,
         vehType: 'boat',
         type: 'faction',
         name: 'القارب السريع',
         level: 0,
         release: 2023,
         price: 0,
         hash: 'defender',
         acceleration: 97.50,
         braking: 0,
         handling: 50.33,
         maxKG: 80,
         Z_Dealership: 0.4
      },
      {
         id: 70,
         vehType: 'truck',
         type: 'faction',
         name: 'السطحة',
         release: 2020,
         price: 300000,
         hash: 'flatbed3',
         speed: 100,
         acceleration: 35.00,
         braking: 8.33,
         handling: 50.00,
         maxKG: 40
      },
      {
         id: 71,
         vehType: 'car',
         type: 'normal',
         category: 'classic_sport',
         name: 'Karin Sultan',
         release: 2018,
         price: 140000,
         hash: 'sultan3',
         level: 12,
         acceleration: 83.00,
         braking: 33.00,
         handling: 76.00,
         maxKG: 20
      },
      {
         id: 72,
         vehType: 'car',
         type: 'faction',
         name: 'القوات الخاصة',
         level: 0,
         release: 2023,
         price: 0,
         hash: 'polpatriotf2',
         acceleration: 60,
         braking: 30,
         handling: 75.76,
         maxKG: 60
      },
      {
         id: 73,
         vehType: 'car',
         type: 'faction',
         name: 'اكسبلور إسعاف',
         level: 0,
         release: 2023,
         price: 0,
         hash: 'EMSExplore',
         acceleration: 60,
         braking: 30,
         handling: 75.76,
         maxKG: 60
      },
      {
         id: 74,
         vehType: 'car',
         type: 'faction',
         name: 'تاهو إسعاف',
         level: 0,
         release: 2023,
         price: 0,
         hash: 'slicktahoek9bb',
         acceleration: 60,
         braking: 30,
         handling: 75.76,
         maxKG: 60
      },
      {
         id: 75,
         vehType: 'car',
         type: 'normal',
         category: 'cargo40',
         name: 'Vapid Contender',
         release: 2020,
         price: 45000,
         hash: 'contender',
         acceleration: 65.00,
         braking: 20.00,
         handling: 63.64,
         maxKG: 40
      },
      {
         id: 77,
         vehType: 'car',
         type: 'normal',
         category: 'sedan',
         name: 'Lincoln Towncar',
         release: 2012,
         price: 50000,
         hash: 'towncar2010',
         level: 11,
         acceleration: 82.00,
         braking: 33.00,
         handling: 76.00,
         maxKG: 20
      },
      {
         id: 78,
         vehType: 'car',
         type: 'normal',
         category: 'cargo120',
         name: 'Chevrolet Silverado',
         release: 2022,
         price: 420000,
         hash: '2020silv',
         level: 30,
         acceleration: 65.00,
         braking: 20.00,
         handling: 63.64,
         maxKG: 120
      },
      {
         id: 79,
         vehType: 'car',
         type: 'store',
         category: 'sport',
         name: 'Aston Vantage',
         release: 2023,
         price: 500000,
         hash: 'vantage',
         level: 38,
         acceleration: 93.75,
         braking: 36.67,
         handling: 81.82,
         maxKG: 20
      },
      {
         id: 80,
         vehType: 'car',
         type: 'normal',
         category: 'coupe',
         name: 'BMW M6',
         release: 2013,
         price: 130000,
         hash: 'm6f13',
         level: 16,
         acceleration: 73.75,
         braking: 36.67,
         handling: 61.82,
         maxKG: 20
      },
      {
         id: 81,
         vehType: 'car',
         type: 'normal',
         category: 'cargo80',
         name: 'Ford F250',
         release: 2023,
         price: 190000,
         hash: '20F250',
         level: 20,
         acceleration: 53.75,
         braking: 26.67,
         handling: 31.82,
         maxKG: 80
      },
      {
         id: 82,
         vehType: 'car',
         type: 'normal',
         category: 'big',
         name: 'Cadillac Escalade',
         release: 2013,
         price: 450000,
         hash: 'esv',
         level: 30,
         acceleration: 77.50,
         braking: 25.00,
         handling: 70.61,
         maxKG: 40
      },
      {
         id: 83,
         vehType: 'car',
         type: 'normal',
         category: 'coupe',
         name: 'Hyundai Genesis',
         release: 2020,
         price: 380000,
         hash: 'genesis',
         level: 18,
         acceleration: 73.75,
         braking: 36.67,
         handling: 61.82,
         maxKG: 20
      },
      {
         id: 84,
         vehType: 'car',
         type: 'normal',
         category: 'cargo80',
         name: 'Dodge Trx',
         release: 2024,
         price: 170000,
         hash: 'trx',
         level: 24,
         acceleration: 77.50,
         braking: 25.00,
         handling: 70.61,
         maxKG: 80
      },
      {
         id: 85,
         vehType: 'car',
         type: 'normal',
         category: 'big',
         name: 'Range Rover EV',
         release: 2023,
         price: 340000,
         hash: 'foxrover1',
         level: 25,
         acceleration: 77.50,
         braking: 25.00,
         handling: 70.61,
         maxKG: 40
      },
      {
         id: 86,
         vehType: 'car',
         type: 'normal',
         category: 'super',
         name: 'BMW i8',
         release: 2023,
         price: 1900000,
         hash: 'i8',
         level: 55,
         acceleration: 77.50,
         braking: 40.00,
         handling: 70.61,
         maxKG: 20
      },
      {
         id: 87,
         vehType: 'car',
         type: 'normal',
         category: 'sport',
         name: 'Chevrolet Camaro',
         release: 2024,
         price: 1500000,
         hash: 'exor',
         level: 50,
         acceleration: 77.50,
         braking: 40.00,
         handling: 70.61,
         maxKG: 20
      },
      {
         id: 88,
         vehType: 'car',
         type: 'normal',
         category: 'sport',
         name: 'Chevrolet C8',
         release: 2024,
         price: 880000,
         hash: 'c8',
         level: 40,
         acceleration: 77.50,
         braking: 40.00,
         handling: 70.61,
         maxKG: 20
      },
      {
         id: 89,
         vehType: 'car',
         type: 'normal',
         category: 'sport',
         name: 'Ford Mustang',
         release: 2021,
         price: 800000,
         hash: 'mustang19',
         level: 45,
         acceleration: 67.50,
         braking: 20.00,
         handling: 60.61,
         maxKG: 20
      },
      {
         id: 90,
         vehType: 'car',
         type: 'normal',
         category: 'sedan',
         name: 'Mercedes Benz',
         release: 2021,
         price: 350000,
         hash: 'BENZS600',
         level: 20,
         acceleration: 67.50,
         braking: 20.00,
         handling: 60.61,
         maxKG: 20
      },
      {
         id: 92,
         vehType: 'car',
         type: 'normal',
         category: 'luxury',
         name: 'Mercedes Maybach',
         release: 2024,
         price: 1000000,
         hash: '19S650',
         level: 35,
         acceleration: 67.50,
         braking: 20.00,
         handling: 60.61,
         maxKG: 20
      },
      {
         id: 93,
         vehType: 'car',
         type: 'normal',
         category: 'sedan',
         name: 'Mercedes C63s',
         release: 2024,
         price: 550000,
         hash: 'c63w205',
         level: 30,
         acceleration: 67.50,
         braking: 20.00,
         handling: 60.61,
         maxKG: 20
      },
      {
         id: 94,
         vehType: 'car',
         type: 'store',
         category: 'coupe',
         name: 'Nissan Skyline',
         release: 2021,
         price: 1000000,
         hash: 'er34',
         level: 1,
         acceleration: 67.50,
         braking: 20.00,
         handling: 60.61,
         maxKG: 20
      },
      {
         id: 95,
         vehType: 'car',
         type: 'store',
         category: 'coupe',
         name: 'Dodge Demon',
         release: 2023,
         price: 1000000,
         hash: 'demon',
         level: 1,
         acceleration: 67.50,
         braking: 20.00,
         handling: 60.61,
         maxKG: 20
      },
      {
         id: 96,
         vehType: 'car',
         type: 'store',
         category: 'off_road',
         name: 'Ford F-350',
         release: 2024,
         price: 1000000,
         hash: 'f350offroadspec',
         level: 1,
         acceleration: 67.50,
         braking: 20.00,
         handling: 60.61,
         maxKG: 160
      },
      {
         id: 97,
         vehType: 'car',
         type: 'store',
         category: 'big',
         name: 'Bentley Bentayga',
         release: 2024,
         price: 1000000,
         hash: 'bentaygast',
         level: 1,
         acceleration: 67.50,
         braking: 20.00,
         handling: 60.61,
         maxKG: 40
      },
      {
         id: 98,
         vehType: 'car',
         type: 'store',
         category: 'super',
         name: 'Lamborghini Aventador',
         release: 2023,
         price: 1000000,
         hash: 'sv',
         level: 1,
         acceleration: 67.50,
         braking: 20.00,
         handling: 60.61,
         maxKG: 20
      },
      {
         id: 99,
         vehType: 'car',
         type: 'store',
         category: 'coupe',
         name: 'BMW M4',
         release: 2021,
         price: 1000000,
         hash: 'm4lb',
         level: 1,
         acceleration: 67.50,
         braking: 20.00,
         handling: 60.61,
         maxKG: 40
      },
      {
         id: 100,
         vehType: 'car',
         type: 'store',
         category: 'coupe',
         name: 'Porche 911',
         release: 2022,
         price: 1000000,
         hash: '911turbos',
         level: 1,
         acceleration: 67.50,
         braking: 20.00,
         handling: 60.61,
         maxKG: 20
      },
      {
         id: 101,
         vehType: 'car',
         type: 'store',
         category: 'coupe',
         name: 'Mercedes AMG',
         release: 2023,
         price: 1000000,
         hash: 'amggtsmansory',
         level: 1,
         acceleration: 67.50,
         braking: 20.00,
         handling: 60.61,
         maxKG: 20
      },
      {
         id: 102,
         vehType: 'car',
         type: 'store',
         category: 'big',
         name: 'Jeep Demonhawk',
         release: 2020,
         price: 1000000,
         hash: 'demonhawk',
         level: 1,
         acceleration: 67.50,
         braking: 20.00,
         handling: 60.61,
         maxKG: 40
      },
      {
         id: 103,
         vehType: 'truck',
         type: 'store',
         category: 'head',
         name: 'NewCola Phantom',
         release: 2019,
         price: 1000000,
         hash: 'phantomcola',
         level: 1,
         acceleration: 67.50,
         braking: 20.00,
         handling: 60.61,
         maxKG: 20
      },
      {
         id: 104,
         vehType: 'truck',
         type: 'store',
         category: 'cargo350',
         name: 'NewCola Trailer',
         release: 2019,
         price: 1000000,
         hash: 'trailerscola',
         level: 1,
         acceleration: 67.50,
         braking: 20.00,
         handling: 60.61,
         maxKG: 350
      },
      {
         id: 105,
         vehType: 'car',
         type: 'store',
         category: 'super',
         name: 'Ferrari 812',
         release: 2023,
         price: 1000000,
         hash: 'f812',
         level: 1,
         acceleration: 67.50,
         braking: 20.00,
         handling: 60.61,
         maxKG: 20
      },
      {
         id: 106,
         vehType: 'truck',
         type: 'store',
         category: 'cargo250',
         name: 'Mercedes Unimog',
         release: 2020,
         price: 1000000,
         hash: 'unimog',
         level: 1,
         acceleration: 67.50,
         braking: 20.00,
         handling: 60.61,
         maxKG: 250
      },
      {
         id: 107,
         vehType: 'car',
         type: 'store',
         category: 'sport',
         name: 'Toyota Supra',
         release: 2023,
         price: 1000000,
         hash: 'a90pit',
         level: 1,
         acceleration: 67.50,
         braking: 20.00,
         handling: 60.61,
         maxKG: 20
      },
      {
         id: 108,
         vehType: 'motorcycle',
         type: 'store',
         category: 'sport',
         name: 'Yamaha R1',
         release: 2021,
         price: 1000000,
         hash: 'm121',
         level: 1,
         acceleration: 67.50,
         braking: 20.00,
         handling: 60.61,
         maxKG: 5
      },
      {
         id: 109,
         vehType: 'car',
         type: 'store',
         category: 'classic',
         name: 'Lincoln Town',
         release: 1997,
         price: 1000000,
         hash: 'towncar79li',
         level: 1,
         acceleration: 67.50,
         braking: 20.00,
         handling: 60.61,
         maxKG: 60
      },
      {
         id: 110,
         vehType: 'car',
         type: 'store',
         category: 'big',
         name: 'Audi RS6',
         release: 2022,
         price: 1000000,
         hash: 'rs6+',
         level: 1,
         acceleration: 67.50,
         braking: 20.00,
         handling: 60.61,
         maxKG: 40
      },
      {
         id: 111,
         vehType: 'truck',
         type: 'normal',
         category: 'other',
         name: 'Brute Van',
         release: 2018,
         price: 7000000,
         hash: 'taco',
         level: 12,
         maxKG: 120
      }
   ]
}